export const SET_ROOM_LIST = 'SET_ROOM_LIST';
export const SET_CHAT_ROOM = 'SET_CHAT_ROOM';
export const SET_CURRENT_ROOM_NAME = 'SET_CURRENT_ROOM_NAME';
export const CLEAR_CURRENT_ROOM_NAME = 'CLEAR_CURRENT_ROOM_NAME';
export const SHOW_CHAT = 'SHOW_CHAT';
export const HIDE_CHAT = 'HIDE_CHAT';
