export const Types = {
  SAVE_FRIENDS_LIST: "SAVE_FRIENDS_LIST",
  SEND_REQUEST_FAILURE:"SEND_REQUEST_FAILURE",
  SAVE_FRIENDS_PENDING_LIST:"SAVE_FRIENDS_PENDING_LIST",
  SET_REQUEST_SUCCESS:"SET_REQUEST_SUCCESS",
  REST_VALUES_TO_DEFAULT:"REST_VALUES_TO_DEFAULT",
  SET_LOADING: "SET_LOADING"
};
