export const SET_NOTIFICATIONS = 'SET_INIT_NOTIFICATION';
export const UPDATE_NOTIFICATIONS = 'UPDATE_NOTIFICATIONS';
export const DELETE_NOTIFICATIONS = 'DELETE_NOTIFICATIONS';
export const SWITCH_NOTIFICATION_TYPE = 'SWITCH_NOTIFICATION_TYPE';
