export const Types = {
  SAVE_PROGRESS_LIST: "SAVE_PROGRESS_LIST",
  SET_LOADING:"SET_LOADING",
  SAVE_PROJECTS_LIST:"SAVE_PROJECTS_LIST",
  SAVE_TRANING_LIST:"SAVE_TRANING_LIST",
  USER_TRIBES_LIST:"USER_TRIBES_LIST"
};
