export const Types = {
  PROJECTS_SET_LOADING: "PROJECT_LIST_SET_LOADING",
  PROJECTS_GET_LIST: "PROJECT_LIST_GET_LIST",
  PROJECTS_SET_LIST: "PROJECT_LIST_SET_LIST",
  PROJECTS_GET_BY_ID: "PROJECTS_GET_BY_ID",
  PROJECTS_SET_CURRENT: "PROJECTS_SET_CURRENT",
  PROJECTS_SET_CURRENT_LOADING: "PROJECTS_SET_CURRENT_LOADING",
};
