export const FETCHING_TODO_LIST_START = "FETCHING_TODO_LIST_START";
export const FETCHING_TODO_LIST_SUCCESS = "FETCHING_TODO_LIST_SUCCESS";
export const FETCHING_USER_NOTE_START = "FETCHING_USER_NOTE_START";
export const FETCHING_USER_NOTE_SUCCESS = "FETCHING_USER_NOTE_SUCCESS";
