export const Types = {
    SAVE_USER_TRIBES: "SAVE_USER_TRIBES",
    SAVE_USER_JOINED_TRIBES:"SAVE_USER_JOINED_TRIBES",
    EDIT_PUBLIC_TRIBE_INFO:"EDIT_PUBLIC_TRIBE_INFO",
    EDIT_PRIVATE_TRIBE_INFO:"EDIT_PRIVATE_TRIBE_INFO"
  };
  