export const Types = {
    SAVE_USER_TRIBES: "SAVE_USER_TRIBES",
    SAVE_USER_JOINED_TRIBES:"SAVE_USER_JOINED_TRIBES",
    EDIT_PUBLIC_TRIBE_INFO:"EDIT_PUBLIC_TRIBE_INFO",
    EDIT_PRIVATE_TRIBE_INFO:"EDIT_PRIVATE_TRIBE_INFO",
    SET_TRIBE_CODE_IN_IFRAME:"SET_TRIBE_CODE_IN_IFRAME",
    SET_TRIBE_EMOJI_CODE:"SET_TRIBE_EMOJI_CODE",
    OPEN_TRIBE_MODAL:"OPEN_TRIBE_MODAL",
    CLOSE_TRIBE_MODAL:"CLOSE_TRIBE_MODAL",
    IS_FIND_TRIBE_LINK_OR_IMG:"IS_FIND_TRIBE_LINK_OR_IMG",
    SET_ERROR_MESSAGE:"SET_ERROR_MESSAGE",
    SET_SUCCESS_MESSAGE:"SET_SUCCESS_MESSAGE",
    SAVE_TRIBES_REQUESTS:"SAVE_TRIBES_REQUESTS"
  };
  