export const Types = {
  SAVE_USER: "SAVE_USER",
  SET_USER_ID: "SET_USER_ID",
  LOADING: "LOADING",
  SET_CODE_IN_IFRAME: "SET_CODE_IN_IFRAME",
  SET_EMOJI_CODE: "SET_EMOJI_CODE",
  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL",
  IS_FIND_LINK_OR_IMG: "IS_FIND_LINK_OR_IMG",
  UPDATE_PUBLIC_USER_INFO: "UPDATE_PUBLIC_USER_INFO",
  EDIT_PRIVATE_USER_INFO: "EDIT_PRIVATE_USER_INFO",
  EDIT_PUBLIC_USER_INFO: "EDIT_PUBLIC_USER_INFO",
  IS_CURRENT_USER: "IS_CURRENT_USER"
};
